### PR TITLE
Add PITest (Java) related Mutation Testing resources

### PR DESCRIPTION
**Pull request by nfrankel**
Talk and posts

### CODE REVIEW

**Comment by theofidry** [comment]
Since they are directly related to PITest (although I understand as such it touches a bit of mutation testing in general), what about moving them under the PITest bullet point like the other resources linked to a specific framework?

**Comment by nfrankel** [comment]
@theofidry Done

**Comment by theofidry** [comment]
Thanks!

**Comment by nfrankel** [comment]
@theofidry Thanks for this initiative! I'm a big fan of mutation testing myself.

**Pull request merged**
